name: Exemplo Actions com Git
on: push
jobs:
  Exemplo-Informacoes-Runner:
    name: Exemplo Informacoes GitHub Actions Runner
    runs-on: ubuntu-latest
    steps:
      # Qual é o ssitema operacioal do Runner?
      - run: echo "${{ runner.os }}"

      # Qual evento iniciou o workflow?
      - run: echo "${{ github.event_name }} evento"

      # Qual repositorio e workflow
      - run:  echo "${{ github.ref }}  repo ${{ github.repository }}"

  Segundo-Job:
    name: Exemplo desegundo job
    runs-on: windows
    needs: Exemplo-Informacoes-Runner
    steps:
      - run: echo "${{ runner.os }}"
